### ISSUE TITLE
Update: Upgrade clap to V3.1.6 & replace deprecated code in main.rs

### ISSUE THREAD

**Issue by PJC-64** [tkellogg/dura#100]
Hi,

while looking into adding the 'status' functionality, I received lots of warnings that clap 3.0.x functionality was now deprecated.

I have updated Cargo.toml & main.rs to use clap V3.1.6 and the new 'Command' functionality in my fork.

I can provide a PR with the changes if wanted.

-Paul (@PJC-64)

**Comment by drupol** [comment]
Hi,

Yes, a PR is much appreciated ;)

Thanks.

**Comment by Amanse** [comment]
Can be closed now :)
