### ISSUE TITLE
`dura capture` has no documentation

### ISSUE THREAD

**Issue by SamuelFountain** [tkellogg/dura#15]
`dura capture` is a valid command in main. However, there is no documentation of the `capture` command *(serve and watch are both documented in README.md)*.

The called fuction/file also contains no comment about the functionality.

**Comment by tkellogg** [comment]
Ah yeah. It's just a single iteration of the control loop. We could remove it entirely, but I keep thinking that there's some use for it. Like if we move to a more complex algorithm for detecting changes we could end up not capturing changes for 20+ minutes in far edge cases. Might be nice to call this explicitly.

**Comment by tkellogg** [comment]
I documented this in the help message in https://github.com/tkellogg/dura/commit/a3bb948c20cf6957e27a59e43b447340008074de
