### ISSUE TITLE
Get author and committer from a config variable or default out.

### ISSUE THREAD

**Issue by ishworgurung** [tkellogg/dura#21]
Neat idea. I think, for dura auto-commit vs. a human commit, it'd be nicer to distinguish the author and committer. 

https://github.com/tkellogg/dura/blob/c5c49d3c8515a3dd3fa068fdb2fb692df9d01c09/src/snapshots.rs#L54

**Comment by tkellogg** [comment]
oh yes! It could be something like `dura@github.io`. I'm not sure about the benefits of having the email be a real email address though.

**Comment by eauxpie** [comment]
also being able to use the git configured author instead of whoever the author of head was. I don't need to distinguish dura commits from my other commits, but I do want them to show up consistently as mine, not whoever last pushed to that branch

**Comment by tkellogg** [comment]
A good approach would be

1. Default to the settings of `git config`
2. Override in the config file

Details around the config file are being hashed out in #25, but we can easily take approach \1 now.
