### ISSUE TITLE
Consider editing repository setings to remove "Packages" section

### ISSUE THREAD

**Issue by matkoniecz** [tkellogg/dura#23]
"Packages No packages published" is displayed right now, fortunately this pointless section can be removed.

Edit repo page config to remove it (cog next to the description).

I am not making a PR as it is defined in proprietary github settings, not in a git repository - and I have no rights to modify repo settings.

![Peek 2020-10-25 09-10](https://user-images.githubusercontent.com/899988/97102018-3a168700-16a2-11eb-8c18-7bd9a88922eb.gif)
Maybe removing also releases section?

**Comment by matkoniecz** [comment]
just in case you were wondering about incoming people - this is caused by https://news.ycombinator.com/item?id=29784238

**Comment by tkellogg** [comment]
fixed, thanks! Yeah, I saw the HN link yesterday, I initially posted it on [lobste.rs](https://lobste.rs/s/g7suro/dura_you_shouldn_t_ever_lose_your_work_if), but HN is definitely a busier place.
