### ISSUE TITLE
Watch multiple directories at once

### ISSUE THREAD

**Issue by tkellogg** [tkellogg/dura#25]
`dura watch` currently only processes the current directory. The readme could become a lot easier if we change `main.rs` to watch all directories passed. It should be a matter of calling `snapshots::create` in a loop.

After that, update the readme with the `find ~ | xargs dura watch` trick.

I personally like this approach because it's extremely flexible. While we'll probably implement more polished ways of discovering repos, someone will always need something like this.

**Comment by pkoch** [comment]
I agree this makes sense, but why delay adding a palliative trick to the README, tho? It'll already help users, and we can adapt it when the changes to `main.rs` come in.

**Comment by tkellogg** [comment]
@pkoch True, no reason to wait.

**Comment by pkoch** [comment]
PR for adding a note to the README in. We could add a note at the top of #3.

Take your pick! :)

**Comment by pkoch** [comment]
Now that #34 is merged, do you still like keeping this issue as a quality of life improvement, or would you rather close it and focus on #3?
