### ISSUE TITLE
Errors when running the fish script 

### ISSUE THREAD

**Issue by SamuelFountain** [tkellogg/dura#38]
I was trying to run the fish script that @alin23  wrote. I ran into some issues with `pgrep`, `command_exists`, and and unmatched `}`. See below for terminal output.

    
    sam@pop-os:~/Documents/repos/dura/scripts$ /usr/bin/env fish ./dura.fish
    pgrep: invalid option -- 'q'
    
    Usage:
     pgrep [options] <pattern>
    
    Options:
     -d, --delimiter <string>  specify output delimiter
     -l, --list-name           list PID and process name
     -a, --list-full           list PID and full command line
     -v, --inverse             negates the matching
     -w, --lightweight         list all TID
     -c, --count               count of matching processes
     -f, --full                use full process name to match
     -g, --pgroup <PGID,...>   match listed process group IDs
     -G, --group <GID,...>     match real group IDs
     -i, --ignore-case         match case insensitively
     -n, --newest              select most recently started
     -o, --oldest              select least recently started
     -O, --older <seconds>     select where older than seconds
     -P, --parent <PPID,...>   match only child processes of the given parent
     -s, --session <SID,...>   match session IDs
     -t, --terminal <tty,...>  match by controlling terminal
     -u, --euid <ID,...>       match by effective IDs
     -U, --uid <ID,...>        match by real IDs
     -x, --exact               match exactly with the command name
     -F, --pidfile <file>      read PIDs from file
     -L, --logpidfile          fail if PID file is not locked
     -r, --runstates <state>   match runstates [D,S,Z,...]
     --ns <PID>                match the processes that belong to the same
                               namespace as <pid>
     --nslist <ns,...>         list which namespaces will be considered for
                               the --ns option.
                               Available namespaces: ipc, mnt, net, pid, user, uts
    
     -h, --help     display this help and exit
     -V, --version  output version information and exit
    
    For more details see pgrep(1).
    fish: Unknown command: command_exists
    ./dura.fish (line 7):
        if command_exists mktemp
           ^
    in function 'tempfile'
        called on line 1 of file ./dura.fish
    in command substitution
        called on line 14 of file ./dura.fish
    WARNING: tempfile is deprecated; consider using mktemp instead.
    fish: Unknown command: command_exists
    ./dura.fish (line 7):
        if command_exists mktemp
           ^
    in function 'tempfile'
        called on line 1 of file ./dura.fish
    in command substitution
        called on line 15 of file ./dura.fish
    WARNING: tempfile is deprecated; consider using mktemp instead.
    parse error: Unmatched '}' at line 1, column 24
    Invalid number of arguments.
    parse error: Unmatched '}' at line 1, column 24
    parse error: Unmatched '}' at line 1, column 24

Working on pop-os (Ubuntu) 

    sam@pop-os:~/Documents/repos/dura/scripts$ fish --version
    fish, version 3.1.2
    sam@pop-os:~/Documents/repos/dura/scripts$ pgrep --version
    pgrep from procps-ng 3.3.17

**Comment by alin23** [comment]
@SamuelFountain can you check if the script in this PR (#39) works?

**Comment by SamuelFountain** [comment]
@alin23 I can confirm that this has fixed all of the issues I had listed. Which of course means I am running into two new kinds of errors, shown below.

    sam@pop-os ~/D/r/d/scripts (master) [SIGINT]> fish ./dura.fish
    Invalid number of arguments.
    inotify_init: Too many open files
    Cannot initialize inotify.
    Status code: 1
    inotify_init: Too many open files
    Cannot initialize inotify.
    Status code: 1
    inotify_init: Too many open files
    Cannot initialize inotify.
    Status code: 1
    inotify_init: Too many open files
    Cannot initialize inotify.
    Status code: 1

I did some testing and I think that the `Invalid number of arguments` is coming from the call `pkill -P`, but I am not sure where the

    inotify_init: Too many open files
    Cannot initialize inotify.
    Status code: 1

Block is coming from

**Comment by alin23** [comment]
That's fswatch calling inotify. 

The thing is, each platform has its own file watch API. The macOS FSEvents is a bit more robust that the Linux inotify, it doesn't fail on too many files, that's why I couldn't foresee these errors.

You need to increase the file limit on your system: https://rtcamp.com/tutorials/linux/increase-open-files-limit/
