### ISSUE TITLE
Shutting down because other poller took lock: None

### ISSUE THREAD

**Issue by jazzdan** [tkellogg/dura#40]
I was running dura yesterday and it was working great. I think I accidentally closed the terminal it was running in and re-opened it, and now when I run `dura serve` I get this error:

```
$ dura serve
pid: 2285
Wrote /Users/dan/.config/dura/config.json
Shutting down because other poller took lock: None
```

My first thought was maybe I had another dura running but I don't think I do:

```
ps aux | grep dura
dan               2168   0.0  0.0 407963440    416 s001  R+   10:02AM   0:00.00 grep dura
```

Running `dura kill` didn't help either, I still get the same error when running `dura serve`.

**Comment by tkellogg** [comment]
I'll see if I can reproduce this in a test.

I'm not sure how it would go into deadlock like this. The algorithm is:

1. start up, write own PID to config.json
2. start loop, check if PID in config.json is same as own PID. If not, exit loop and fail process.
3. do work, go to 2.

If a process dies unexpectedly, the new process will overwrite & take control. `dura kill` overwrites the PID with `None`/`null` so it effectively stops all processes.

The behavior you're describing seems to be that `dura kill` is running on repeat. 

Are you running on Docker or an overlay filesystem? Ive seen strange behavior like this on Docker (overwrites not being recognized/consistent).

**Comment by jazzdan** [comment]
@tkellogg ah sorry, I should have included the environment. I'm running dura on macOS 12.0.1 arm64.

I tried `git pull`'ing my dura repo and re-installing. Now when I run `dura serve` or `dura kill` both hang with no output. Interesting!

**Comment by tkellogg** [comment]
can you check the logs in `~/.config/dura/logs/`

also i wouldn't mind seeing a `ls -lathr ~/.config/dura/` and also the config file.

**Comment by tkellogg** [comment]
I just tracked down the issue. I'll push out a fix as soon as I can. The problem is that the json file gets corrupted when overwriting with a shorter file. i.e. "overwrite" isn't what I normally think of as overwrite since it doesn't reduce the length of the file.

In your case, i think you might have restarted your laptop, which caused the PID count to reset to a shorter number, shortening the length of the file.

**Comment by tkellogg** [comment]
Thanks for submitting this one. I don't know how I got so far without seeing it.

**Comment by jazzdan** [comment]
Ahh good catch @tkellogg !! Thanks for the fix and for making dura :)

**Comment by jazzdan** [comment]
@tkellogg you're theory was right by the way, here's what my `config.json` looks like:

```json
{"pid":57878,"repos":{}}sers/dan/devel/backend":{}}}}%      
```
