### ISSUE TITLE
Better CLI implementation

### ISSUE THREAD

**Issue by JakeStanger** [tkellogg/dura#51]
The current CLI is fine, but the need to be in the current directory for some operations is a little annoying. The current implementation also makes it difficult to expand for more features (such as the `WatchConfig` fields added in #49 ). 

I would suggest initially migrating the current code to use [Clap](https://github.com/clap-rs/clap) or similar. 

Commands could then be updated to the something like the below format:

```
dura serve # can be left as-is

# these default to cwd
dura watch [dir] [--include <includes>] [--exclude <excludes>] [--max-depth <depth>]
dura unwatch [dir]
dura capture [dir]
```

**Comment by tkellogg** [comment]
Definitely. This would be a huge improvement.

**Comment by drupol** [comment]
Working on clap integration, working fine so far.

![image](https://user-images.githubusercontent.com/252042/148661913-8c2130ec-259e-4987-b847-f80a364d6431.png)

**Comment by tkellogg** [comment]
@JakeStanger does this resolve the issue adequately?

**Comment by JakeStanger** [comment]
Absolutely, that's fantastic service! Awesome and very speedy work @drupol

**Comment by drupol** [comment]
Thanks! It's the second time I do a PR for a rust project, I really like it !
