### ISSUE TITLE
Build Fail: Can't find GLIBC

### ISSUE THREAD

**Issue by tkellogg** [tkellogg/dura#56]
@drupol This definitely seems like a NixOS environment issue. Can you take a look? On Ubuntu it's usually solved with installing some C/C++ tools, like `gcc`. Not really sure about NixOS.

https://github.com/tkellogg/dura/runs/4750159031?check_suite_focus=true

**Comment by drupol** [comment]
I already provided a commit to fix this: https://github.com/tkellogg/dura/pull/55/commits/69f10e6a36fa5fc615b4e7e1b193771297e0b8cb

**Comment by tkellogg** [comment]
1. I don't see this commit in a pull request or `master`, AFAICT
2. Why does fixing Ubuntu fix NixOS?

**Comment by drupol** [comment]
> 1. I don't see this commit in a pull request or `master`, AFAICT

It is in #55 I'm trying to understand the issue as well.

>     2. Why does fixing Ubuntu fix NixOS?

I don't know yet, I'm just trying to understand what is going on...

**Comment by drupol** [comment]
I have something working here: https://github.com/drupol/dura/runs/4750381063

But it's not using Nix. I'm going to investigate on my own to understand the root of the issue.

**Comment by tkellogg** [comment]
closed by #55
